language: ruby
rvm:
  - 2.3.1
before_install:
  # Upgrade to Bundler 2.0 to match the lockfile.
  - gem update --system
  - gem install bundler
script:
  - gem install bundler
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
